builds:
  - binary: kubeum
    main: ./cli/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
  - binary: api-kubeum
    main: ./api/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
  vendor: Baptiste Mayelle
  homepage: https://github.com/youkoulayley/kubeum
  maintainer: Baptiste Mayelle
  description: Kubernetes User Managment
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
