apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kubeum
  namespace: kube-system
  labels:
    app: api-kubeum
spec:
  replicas: 1
  template:
    metadata:
      name: api-kubeum
      labels:
        app: api-kubeum
    spec:
      containers:
      - name: api-kubeum
        image: youkoulayley/api-kubeum:latest
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: "APP_PORT"
            value: "8080"
          - name: "API_SERVER_URL"
            value: "https://localhost:6443"
          - name: "LOG_LEVEL"
            value: "Info"
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
            scheme: HTTP
      restartPolicy: Always
      serviceAccountName: api-kubeum
  selector:
    matchLabels:
      app: api-kubeum
---
apiVersion: v1
kind: Service
metadata:
  name: api-kubeum
  namespace: kube-system
spec:
  selector:
    app: api-kubeum
  ports:
    - port: 8080
      nodePort: 31000
  type: NodePort
