apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-get-kubeconfig
rules:
  - verbs:
      - "get"
      - "list"
      - "watch"
    apiGroups:
      - ""
      - "*"
    resources:
      - "serviceaccounts"
      - "secrets"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-get-kubeconfig
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-get-kubeconfig
subjects:
  - kind: ServiceAccount
    name: kube-get-kubeconfig
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-get-kubeconfig
  namespace: kube-system

